/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CapacitacoesRouteImport } from './routes/capacitacoes'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacoesRoute = CapacitacoesRouteImport.update({
  id: '/capacitacoes',
  path: '/capacitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/capacitacoes': typeof CapacitacoesRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/capacitacoes': typeof CapacitacoesRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/capacitacoes': typeof CapacitacoesRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areas-de-atuacao' | '/capacitacoes' | '/contato' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas-de-atuacao' | '/capacitacoes' | '/contato' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/areas-de-atuacao'
    | '/capacitacoes'
    | '/contato'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  CapacitacoesRoute: typeof CapacitacoesRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacoes': {
      id: '/capacitacoes'
      path: '/capacitacoes'
      fullPath: '/capacitacoes'
      preLoaderRoute: typeof CapacitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  CapacitacoesRoute: CapacitacoesRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
